
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../src",
  "Ext.data.ProxyMgr": "../../src/app/Application.js",
  "Ext.device.Purchases.Product": "../../src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../src/draw/engine/SvgContext.js",
  "Kitchensink": "app",
  "Kitchensink.util.Proxy": "app/store/Speakers.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Kitchensink.controller.Main": [],
  "Kitchensink.controller.phone.Main": [],
  "Kitchensink.controller.tablet.Main": [],
  "Kitchensink.controller.windowsphone.Main": [],
  "Kitchensink.model.Cars": [],
  "Kitchensink.model.Contact": [],
  "Kitchensink.model.Demo": [],
  "Kitchensink.model.OHLC": [],
  "Kitchensink.model.Order": [],
  "Kitchensink.model.OrderItem": [],
  "Kitchensink.model.Speaker": [],
  "Kitchensink.model.User": [],
  "Kitchensink.profile.Base": [],
  "Kitchensink.profile.Phone": [],
  "Kitchensink.profile.Tablet": [],
  "Kitchensink.store.Demos": [],
  "Kitchensink.store.List": [],
  "Kitchensink.store.OrderItems": [],
  "Kitchensink.store.Pie": [],
  "Kitchensink.store.Speakers": [],
  "Kitchensink.store.StockPrice": [],
  "Kitchensink.store.USD2EUR": [],
  "Kitchensink.util.Proxy": [],
  "Kitchensink.view.Ajax": [],
  "Kitchensink.view.AreaChart": [],
  "Kitchensink.view.Audio": [],
  "Kitchensink.view.BarChart": [],
  "Kitchensink.view.BasicDataView": [],
  "Kitchensink.view.BasicList": [],
  "Kitchensink.view.BottomTabs": [],
  "Kitchensink.view.BubbleChart": [],
  "Kitchensink.view.Buttons": [],
  "Kitchensink.view.CandlestickChart": [],
  "Kitchensink.view.Carousel": [],
  "Kitchensink.view.ColorPatterns": [],
  "Kitchensink.view.ColumnChart": [],
  "Kitchensink.view.ColumnChart3D": [],
  "Kitchensink.view.ColumnChartStacked": [],
  "Kitchensink.view.ColumnChartWithRenderer": [],
  "Kitchensink.view.ColumnSeries3D": [],
  "Kitchensink.view.CoverDown": [],
  "Kitchensink.view.CoverLeft": [],
  "Kitchensink.view.CoverRight": [],
  "Kitchensink.view.CoverUp": [],
  "Kitchensink.view.Cube": [],
  "Kitchensink.view.DisclosureList": [],
  "Kitchensink.view.EditorPanel": [],
  "Kitchensink.view.Fade": [],
  "Kitchensink.view.Flip": [],
  "Kitchensink.view.FormPanel": [],
  "Kitchensink.view.FreeDraw": [],
  "Kitchensink.view.FreeDrawComponent": [],
  "Kitchensink.view.GalleryPage": [],
  "Kitchensink.view.GaugeChart": [],
  "Kitchensink.view.GroupedList": [],
  "Kitchensink.view.HorizontalDataView": [],
  "Kitchensink.view.Icons": [],
  "Kitchensink.view.InlineDataView": [],
  "Kitchensink.view.JSONP": [],
  "Kitchensink.view.LineChart": [],
  "Kitchensink.view.LineChartWithMarker": [],
  "Kitchensink.view.LineChartWithRenderer": [],
  "Kitchensink.view.LoremIpsum": [],
  "Kitchensink.view.LoremIpsum2": [],
  "Kitchensink.view.Map": [],
  "Kitchensink.view.NestedList": [],
  "Kitchensink.view.NestedLoading": [],
  "Kitchensink.view.OHLCChart": [],
  "Kitchensink.view.Overlays": [],
  "Kitchensink.view.PieChart": [],
  "Kitchensink.view.PieChart3D": [],
  "Kitchensink.view.PlotChart": [],
  "Kitchensink.view.Pop": [],
  "Kitchensink.view.RadarChart": [],
  "Kitchensink.view.RevealDown": [],
  "Kitchensink.view.RevealLeft": [],
  "Kitchensink.view.RevealRight": [],
  "Kitchensink.view.RevealUp": [],
  "Kitchensink.view.ScatterChart": [],
  "Kitchensink.view.SlideDown": [],
  "Kitchensink.view.SlideLeft": [],
  "Kitchensink.view.SlideRight": [],
  "Kitchensink.view.SlideUp": [],
  "Kitchensink.view.Sliders": [],
  "Kitchensink.view.SourceOverlay": [],
  "Kitchensink.view.Tabs": [],
  "Kitchensink.view.ThemeAuto": [],
  "Kitchensink.view.ThemeBB": [],
  "Kitchensink.view.ThemeSencha": [],
  "Kitchensink.view.ThemeWindows": [],
  "Kitchensink.view.ToolbarInput": [],
  "Kitchensink.view.Toolbars": [],
  "Kitchensink.view.TouchEvents": [],
  "Kitchensink.view.VectorIcons": [],
  "Kitchensink.view.Video": [],
  "Kitchensink.view.XRay": [],
  "Kitchensink.view.YQL": [],
  "Kitchensink.view.phone.Main": [],
  "Kitchensink.view.phone.TouchEvents": [],
  "Kitchensink.view.sprite.Column3D": [],
  "Kitchensink.view.tablet.Main": [],
  "Kitchensink.view.tablet.NavigationBar": [],
  "Kitchensink.view.tablet.NestedList": [],
  "Kitchensink.view.tablet.TouchEvents": [],
  "Kitchensink.view.touchevent.Info": [],
  "Kitchensink.view.touchevent.Logger": [],
  "Kitchensink.view.touchevent.Pad": []
});
Ext.ClassManager.addNameAliasMappings({
  "Kitchensink.controller.Main": [],
  "Kitchensink.controller.phone.Main": [],
  "Kitchensink.controller.tablet.Main": [],
  "Kitchensink.controller.windowsphone.Main": [],
  "Kitchensink.model.Cars": [],
  "Kitchensink.model.Contact": [],
  "Kitchensink.model.Demo": [],
  "Kitchensink.model.OHLC": [],
  "Kitchensink.model.Order": [],
  "Kitchensink.model.OrderItem": [],
  "Kitchensink.model.Speaker": [],
  "Kitchensink.model.User": [],
  "Kitchensink.profile.Base": [],
  "Kitchensink.profile.Phone": [],
  "Kitchensink.profile.Tablet": [],
  "Kitchensink.store.Demos": [
    "store.Demos"
  ],
  "Kitchensink.store.List": [
    "store.List"
  ],
  "Kitchensink.store.OrderItems": [
    "store.OrderItems"
  ],
  "Kitchensink.store.Pie": [
    "store.Pie"
  ],
  "Kitchensink.store.Speakers": [],
  "Kitchensink.store.StockPrice": [
    "store.StockPrice"
  ],
  "Kitchensink.store.USD2EUR": [
    "store.USD2EUR"
  ],
  "Kitchensink.util.Proxy": [],
  "Kitchensink.view.Ajax": [],
  "Kitchensink.view.AreaChart": [],
  "Kitchensink.view.Audio": [],
  "Kitchensink.view.BarChart": [],
  "Kitchensink.view.BasicDataView": [],
  "Kitchensink.view.BasicList": [],
  "Kitchensink.view.BottomTabs": [],
  "Kitchensink.view.BubbleChart": [],
  "Kitchensink.view.Buttons": [],
  "Kitchensink.view.CandlestickChart": [],
  "Kitchensink.view.Carousel": [],
  "Kitchensink.view.ColorPatterns": [],
  "Kitchensink.view.ColumnChart": [],
  "Kitchensink.view.ColumnChart3D": [],
  "Kitchensink.view.ColumnChartStacked": [],
  "Kitchensink.view.ColumnChartWithRenderer": [],
  "Kitchensink.view.ColumnSeries3D": [
    "series.column3d"
  ],
  "Kitchensink.view.CoverDown": [],
  "Kitchensink.view.CoverLeft": [],
  "Kitchensink.view.CoverRight": [],
  "Kitchensink.view.CoverUp": [],
  "Kitchensink.view.Cube": [],
  "Kitchensink.view.DisclosureList": [],
  "Kitchensink.view.EditorPanel": [],
  "Kitchensink.view.Fade": [],
  "Kitchensink.view.Flip": [],
  "Kitchensink.view.FormPanel": [],
  "Kitchensink.view.FreeDraw": [],
  "Kitchensink.view.FreeDrawComponent": [],
  "Kitchensink.view.GalleryPage": [],
  "Kitchensink.view.GaugeChart": [],
  "Kitchensink.view.GroupedList": [],
  "Kitchensink.view.HorizontalDataView": [],
  "Kitchensink.view.Icons": [],
  "Kitchensink.view.InlineDataView": [],
  "Kitchensink.view.JSONP": [],
  "Kitchensink.view.LineChart": [],
  "Kitchensink.view.LineChartWithMarker": [],
  "Kitchensink.view.LineChartWithRenderer": [],
  "Kitchensink.view.LoremIpsum": [
    "widget.loremipsum"
  ],
  "Kitchensink.view.LoremIpsum2": [
    "widget.loremipsum2"
  ],
  "Kitchensink.view.Map": [],
  "Kitchensink.view.NestedList": [],
  "Kitchensink.view.NestedLoading": [],
  "Kitchensink.view.OHLCChart": [],
  "Kitchensink.view.Overlays": [],
  "Kitchensink.view.PieChart": [],
  "Kitchensink.view.PieChart3D": [],
  "Kitchensink.view.PlotChart": [],
  "Kitchensink.view.Pop": [],
  "Kitchensink.view.RadarChart": [],
  "Kitchensink.view.RevealDown": [],
  "Kitchensink.view.RevealLeft": [],
  "Kitchensink.view.RevealRight": [],
  "Kitchensink.view.RevealUp": [],
  "Kitchensink.view.ScatterChart": [],
  "Kitchensink.view.SlideDown": [],
  "Kitchensink.view.SlideLeft": [],
  "Kitchensink.view.SlideRight": [],
  "Kitchensink.view.SlideUp": [],
  "Kitchensink.view.Sliders": [],
  "Kitchensink.view.SourceOverlay": [
    "widget.sourceoverlay"
  ],
  "Kitchensink.view.Tabs": [],
  "Kitchensink.view.ThemeAuto": [],
  "Kitchensink.view.ThemeBB": [],
  "Kitchensink.view.ThemeSencha": [],
  "Kitchensink.view.ThemeWindows": [],
  "Kitchensink.view.ToolbarInput": [],
  "Kitchensink.view.Toolbars": [],
  "Kitchensink.view.TouchEvents": [
    "widget.touchevents"
  ],
  "Kitchensink.view.VectorIcons": [
    "widget.vicon"
  ],
  "Kitchensink.view.Video": [],
  "Kitchensink.view.XRay": [
    "sprite.xray"
  ],
  "Kitchensink.view.YQL": [],
  "Kitchensink.view.phone.Main": [],
  "Kitchensink.view.phone.TouchEvents": [],
  "Kitchensink.view.sprite.Column3D": [
    "sprite.columnSeries3d"
  ],
  "Kitchensink.view.tablet.Main": [
    "widget.mainview"
  ],
  "Kitchensink.view.tablet.NavigationBar": [
    "widget.tabletnavigationbar"
  ],
  "Kitchensink.view.tablet.NestedList": [
    "widget.tabletnestedlist"
  ],
  "Kitchensink.view.tablet.TouchEvents": [],
  "Kitchensink.view.touchevent.Info": [
    "widget.toucheventinfo"
  ],
  "Kitchensink.view.touchevent.Logger": [
    "widget.toucheventlogger"
  ],
  "Kitchensink.view.touchevent.Pad": [
    "widget.toucheventpad"
  ]
});
